bot/chatgpt/chat_gpt_bot.py
bridge/bridge.py

修改为使用https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/Official.py的chatgpt

修改为使用chatgpt

---

.gitignore
README.md
channel/wechat/wechaty_channel.py
config-template.json

1. 新增wechaty方案的语音识别、语音回复功能；
2. 更新README；
3. 更新config-template.json文件，将语音识别、回复相关配置、百度AI配置加入；
4. 更新.gitignore文件，将.wechaty/ 目录加入排除项；
语音识别和回复所需依赖如下：
pip3 install pysilk
pip3 install pysilk-mod
pip3 install pydub

 1.新增wechaty方案的语音识别、语音回复功能；2.更新README；

---

bot/chatgpt/chat_gpt_bot.py
common/token_bucket.py

事情源于最近的commit: [增加hot_reload特性开关](https://github.com/zhayujie/chatgpt-on-wechat/commit/3ef7855384852d6733bd9af0e370a23d1a056568)
hot_reload不与服务器同步登录后接受消息的状态，如果和bot大量互动后使用hot_reload会短时间响应大量历史信息，这边观测到峰值达到200tps，远远超过了openai提供给免费用户的速率限制：
为了避免被服务器识别为攻击行为，因此这边做了主动限速的commit，值得一提是RateLimitError错误处理是有必要的，因为openai也对tokens数做了限制
该功能为可选，可在config.json自由使用

feature(rate-limit): 新增令牌桶类，用于主动限制调用gpt3.5, dalle接口频率

---

channel/wechat/wechaty_channel.py

Wechaty判断`is_at`为`True`，返回的内容是过滤掉@之后的内容；而`is_at`为`False`，则会返回完整的内容
以上的情况导致`check_prefix`函数无法处理后者，拿到的内容是”前缀 关键词“，`check_prefix`需要拿到就是`关键词`才能判断是不是进入生成AI图片的功能
故判断如果匹配到自定义前缀，则返回过滤掉前缀+空格后的内容，用于实现类似自定义+前缀触发生成AI图片的功能

支持Wechaty的自定义前缀+关键词生成AI图片的功能

---

README.md
bot/bot_factory.py
bot/chatgpt/chat_gpt_bot.py
bridge/bridge.py
common/const.py
config-template.json

一种替换openai chatgpt service的方法是使用Azure推出的[ChatGPT service](https://azure.microsoft.com/en-in/products/cognitive-services/openai-service/)。它host在公有云Azure上，因此不需要VPN就可以直接访问。不过目前仍然处于preview阶段。新用户可以通过Try Azure for free来薅一段时间的羊毛

Support Azure hosted chatgpt service

---

README.md
bot/chatgpt/chat_gpt_bot.py

安装tiktoken包后能够精确计算token数量，避免prompt超出上限。
如果未安装tiktoken，则仍使用默认方式，但prompt有超出上限的风险，API会报错。

feat: support calc tokens precisely

---

bot/chatgpt/chat_gpt_bot.py
bot/chatgpt/chat_gpt_session.py
bot/openai/open_ai_bot.py
bot/openai/open_ai_image.py
bot/openai/open_ai_session.py
bot/session_manager.py
plugins/dungeon/dungeon.py
plugins/godcmd/godcmd.py
plugins/role/role.py

1. 重构openai image api为单独的类
2. 重构session manager，它可用于管理不同Bot的Session。
3. 得益于1 2，插件新增OpenAIBot的支持。

refactor and support plugins for OpenAIBot

---

README.md
channel/wechat/wechaty_channel.py
config-template.json
config.py

- 新增配置：group_speech_recognition: true # 是否开启群组语音识别
- 原有配置：voice_reply_voice: true    # 是否开启语音回复
1. 关键词匹配和文本消息一样，机器人默认回复文本消息；
2. 关键词匹配到画图等配置时，机器人回复图片；
3. 当voice_reply_voice为true时，机器人回复语音消息；

Wechaty方案下添加对群组语音消息的响应

---

bot/chatgpt/chat_gpt_bot.py
bot/chatgpt/chat_gpt_session.py
config-template.json
config.py

resole exception: "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."

修复适配azure的问题

---

plugins/tool/README.md
plugins/tool/tool.py

tool-hub
1. 新增私有部署的搜索工具： [searxng-search](https://github.com/goldfishh/chatgpt-tool-hub/blob/master/docs/apply_optional_tool.md#6-searxng-search)
2. 修复win系统使用summary临时创建文件后删除的异常 
3. morning-news 新增可配置参数：morning_news_use_llm 用于开关api返回后再处理
4. 新增arxiv工具，用于搜索论文
5. 更改tool engine 核心prompt，使用json格式输出llm-os内心独白、工具和工具输入
6. 修复news子工具返回内容包含乱码信息

plugin(tool): 更新0.4.2

---

bot/chatgpt/chat_gpt_bot.py
channel/chat_channel.py
plugins/godcmd/godcmd.py

feat(命令): 添加set_gpt_model、set_gpt_model、set_gpt_model 几个命令的使用

---

voice/baidu/baidu_voice.py

百度语音的sdk初始化时会对参数进行strip，所以要保证是字符串。否则会报错
> [INFO][2023-06-09 11:04:01][bridge.py:30] - create bot baidu for voice_to_text
﻿[WARNING][2023-06-09 11:04:01][baidu_voice.py:59] - BaiduVoice init failed: 'int' object has no attribute 'strip', ignore
﻿[ERROR][2023-06-09 11:04:01][chat_channel.py:267] - Worker return exception: 'BaiduVoice' object has no attribute 'client'
https://github.com/Baidu-AIP/python-sdk/blob/e9add82014dec830a1b84c2b145a9faf40a84fc7/aip/base.py#LL42C11-L42C11

fix： baidu voice init params type error

---

plugins/tool/README.md

Update Tool README.md

---

plugins/tool/tool.py
requirements-optional.txt

(tool)fix azure model

---

docker/Dockerfile.latest

Python 3.10-slim based Debian 12, using Azure TextToVoice may result in an error. the Speech SDK does not currently support OpenSSL 3.0, which is the default version in Ubuntu 22.04 and Debian 12

dockerfile fallback debian11,fix azure cognitiveservices speech error

---

README.md
bot/claude/claude_ai_bot.py
bot/claude/claude_ai_session
config.py

1.之前传的claude 忘记实现共享上下文的开关功能对接,因为claude接口是指定id实现上下文对应而非message形式，采用了自定义conversation_share_check函数 进行 session_id 与 历史对话id的比对(用户透明)，总开关与项目的 group_chat_in_one_session参数保持一致。
2.更新了下文档
3.美化此接口部分代码格式、缩进

实现claude对接配置中的 共享上下文开关

---

config.py
plugins/hello/hello.py
plugins/source.json

1、增加"group_welcome_msg"可选参数，配置微信群聊新人入群自定义欢迎语；
2、增加apilot插件地址，该插件可以快速获取天气、早报、热榜、快递等实用信息。

自定义入群欢迎语和apilot插件

---

plugins/plugin_manager.py

取消了已载入的插件判断，重载除Godcmd以外的所有插件来实现不需要重启项目即可更新插件

由于使用#scanp和#reloadp扫描插件时，当更新已存在的插件以后并不会实现重载更新后的插件

---

bot/gemini/google_gemini_bot.py

1.调用gemini api出现异常时没有向下游返回错误信息，后续处理流程可能要根据错误信息做相应补偿机制 2.修复特殊场景中出现索引越界导导致应用退出

修复gemini 插件的两个问题

---

config.py
requirements-optional.txt
voice/edge/edge_voice.py
voice/factory.py

Related to this issue https://github.com/zhayujie/chatgpt-on-wechat/issues/1047
A completely free speech synthesis based on reverse engineering of the Edge browser [edge-tts](https://github.com/rany2/edge-tts) (need internet). The effect is exactly the same as Azure in terms of tone and voice, without the need for Azure API. 
You only need to `pip install edge-tts`, and set the `text_to_voice` to `edge`.
The default tune is `zh-CN-YunjianNeural`, native chinese. You can change tone in [`voice\edge\edge_voice.py`](https://github.com/zhayujie/chatgpt-on-wechat/pull/1787/files#diff-41f63f5bcf70be5666114b14da8341d44e9227a94a42811fc37ba5588389cdd0R35). `edge-tts --list-voices` shows all options.

feat: edge-tts 

---

channel/wechat/wechat_channel.py

使用replytype = IMAGE时候，无法正常发送图片，但是日志没有报错
加上这段代码，可以正常发送图片

fix ReplyType.IMAGE 回复图片为空的BUG

---

requirements-optional.txt
voice/elevent/elevent_voice.py

修复 Issues #1868提到的elevenlabs sdk更新问题

---

plugins/linkai/summary.py

微信变更了网页版的链接规则，需要通过解析把`&amp;`转换成`&`，不然itchat的机器人就会无法解析，官方的机器人已经失效了，可能大佬没关注到

新增url解析逻辑，解决itchat中分享卡片无法解析的问题

---

voice/openai/openai_voice.py

解决openai语音识别问题，作者用的是`openai==0.27.8`，好多调用方法都可能弃用了，包括
https://github.com/zhayujie/chatgpt-on-wechat/blob/31ac80a07479dfc85f51d5a20087a492003d7aea/voice/openai/openai_voice.py#L24
故改为比较原始的用`requests`发请求，作者可以考虑一下升级`openai-python`的版本，现在最新的已经到`openai==1.17.1`了。
目前的修改仅仅是为了能用，不是一个完美的解决方案。
解决：
https://github.com/zhayujie/chatgpt-on-wechat/issues/1717
https://github.com/zhayujie/chatgpt-on-wechat/issues/1666
https://github.com/zhayujie/chatgpt-on-wechat/issues/1638
https://github.com/zhayujie/chatgpt-on-wechat/issues/1618
https://github.com/zhayujie/chatgpt-on-wechat/issues/1540

fix openai voice_to_text whisper

---

voice/factory.py
voice/xunfei/config.json.template
voice/xunfei/xunfei_asr.py
voice/xunfei/xunfei_tts.py
voice/xunfei/xunfei_voice.py

基于讯飞的官方demo，做了2个asr和tts的函数（尝试过合并成一个文件，没成功，就还是按官方的2个demo做成了2个文件），再在xunfei_voice中调用这2个函数，
第一次做pull，有问题请联系我，谢谢！

add xunfei voice

---

config.py

解决了drag_sensitive函数中因尝试将列表项字符串进行连接而导致的TypeError问题。详见 #2094 和 #2096

Fix TypeError in config drag_sensitive function

---

docker/docker-compose.yml

由于 docker 容器默认时区为0时区，在时间方面就会与东8区时间不一致。比如在使用 timetask 插件配置定时任务时，时间就会慢8小时。

fix：在docker-compose.yml文件中增加时区设置

---

bot/xunfei/xunfei_spark_bot.py
config.py

支持了讯飞Spark4.0 Ultra模型，并优化了讯飞模型配置的方式，在根目录的配置文件配置如下参数：
{
"xunfei_app_id": "f75345dc",
"xunfei_api_key": "035cac614a5074771",
"xunfei_api_secret": "ZTc5NmY0dl5ODE3OTcyMGJi",
"xunfei_domain": "4.0Ultra",
"xunfei_spark_url": "wss://spark-api.xf-yun.com/v4.0/chat",
}
- `"xunfei_app_id"`：应用创建及参数获取参考： [讯飞平台简介](https://www.xfyun.cn/doc/platform/quickguide.html)
-  `"xunfei_domain"`： 讯飞模型对应的domain参数，Spark4.0 Ultra为 `4.0Ultra`，其他模型详见: [星火认知大模型Web API文档](https://www.xfyun.cn/doc/spark/Web.html)
- `"xunfei_spark_url"`:  讯飞模型对应的请求地址，Spark4.0 Ultra为 `wss://spark-api.xf-yun.com/v4.0/chat`，其他模型参考详见: [星火认知大模型Web API文档](https://www.xfyun.cn/doc/spark/Web.html)

Support Spark4.0 Ultra model, optimize model configuration.

---

channel/wechat/wechat_message.py

加入了notes_join_group,notes_exit_group,notes_patpat列表，可以在加入群聊，退出群聊和拍一拍消息中匹配更多的字符。在此完成了英语(invited, removed, tickled)的匹配，使如果微信语言是英文的话也可以正常识别啦！同时，以后也可以通过加list和判断语句的方式支持更多语言！

支持更多语言（英语）的微信客户端

---

channel/wechatcom/wechatcomapp_channel.py

企微自建应用，取消管理员添加成员到应用可见范围时自动发送订阅消息的功能，避免变动权限时给成员造成干扰。
如需给成员批量发送信息，可以进入[企微后台](https://work.weixin.qq.com/wework_admin/frame#/apps)，进入应用，使用应用的”**发送消息**“功能

Cancel subscribe_msg of wechatcomapp channel

---

bot/moonshot/moonshot_bot.py
bridge/bridge.py

修复`"model": "moonshot"`时，无法路由到对应的bot，并默认指向`"moonshot-v1-32k"`模型

fix: "model":"mooshoot", which defaults to "moonshot-v1-32k".

---

README.md
run.sh

1、新增项目一键安装脚本：[一键安装(启动)脚本](https://github.com/zhayujie/chatgpt-on-wechat/wiki/%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E5%90%AF%E5%8A%A8%E8%84%9A%E6%9C%AC)
```
bash <(curl -sS https://cdn.link-ai.tech/code/cow/install.sh)
```
2、新增项目管理脚本：[项目管理脚本](https://github.com/zhayujie/chatgpt-on-wechat/wiki/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86%E8%84%9A%E6%9C%AC)。在项目根目录下执行：
```bash
chmod +x run.sh 
./run.sh 
./run.sh start
./run.sh stop
./run.sh restart
./run.sh update
```

feat: add install.sh and run.sh

---

channel/wechat/wechat_channel.py
channel/wechatcom/wechatcomapp_channel.py
channel/wechatmp/wechatmp_channel.py
common/utils.py

优化微信、企微自建应用、公众号渠道中的markdown格式符号展示

Optimize markdown format display

---

channel/wechat/wechat_message.py

fix: group patpat notes

---

plugins/linkai/README.md
plugins/linkai/linkai.py
plugins/linkai/midjourney.py
plugins/linkai/summary.py
plugins/linkai/utils.py

支持`/plugins/linkai`插件除了[本地配置或者指令开启](https://github.com/zhayujie/chatgpt-on-wechat/blob/master/plugins/linkai/README.md)以外，还可以通过在linkai平台通过[应用的插件配置](https://link-ai.tech/console/factory)来开启(关闭):
- 私聊：可以通过根目录参数`linkai_app_code`配置应用，在LinkAI平台找到该应用，添加并开启(关闭)MJ插件/内容总结插件
- 群聊：需要先通过`/plugins/linkai/config.json`里的`group_app_map`参数配置群聊对应的应用，或者通过指令`$linkai app <app_code>`来给群聊绑定应用，然后在LinkAI平台找到该应用，添加并开启MJ/内容总结插件。
注：
1、如果只想部分群聊开启mj/总结功能，可以把`/plugins/linkai/config.json`文件里`"summary"`相关的配置关闭，在LinkAI平台，把这些群聊对应应用的mj/总结插件打开即可
2、后续很快兼容LinkAI平台应用**内容总结**插件的自定义提示词功能

Summary and MJ  support can be configured through LinkAI platform app plugins

---

common/linkai_client.py
config.py
plugins/godcmd/godcmd.py
plugins/linkai/linkai.py
plugins/plugin.py
plugins/plugin_manager.py

- Use write_plugin_config() instead of directly modifying plugin_config dict
- Add remove_plugin_config() to clear plugin config before reload
- Update plugins to use pconf() and write_plugin_config() for better config management

fix(plugin): fix reloadp command not taking effect

---

README.md
bot/chatgpt/chat_gpt_session.py
common/const.py

新增Gitee AI模型资源，兼容openai格式，目前支持的对话模型列表：
```
["Yi-34B-Chat", "InternVL2-8B", "deepseek-coder-33B-instruct", "InternVL2.5-26B", "Qwen2-VL-72B", "Qwen2.5-32B-Instruct", "glm-4-9b-chat", "codegeex4-all-9b", "Qwen2.5-Coder-32B-Instruct", "Qwen2.5-72B-Instruct", "Qwen2.5-7B-Instruct", "Qwen2-72B-Instruct", "Qwen2-7B-Instruct", "code-raccoon-v1", "Qwen2.5-14B-Instruct"]
```
更多模型见：[serverless-api](https://ai.gitee.com/serverless-api#)
API_KEY获取：在 Gitee AI 工作台 - 设置 - 访问令牌，复制访问令牌（API key）
配置文件修改：
```
"bot_type": "chatGPT",
"model": "Qwen2.5-72B-Instruct",
"open_ai_api_key": "K8CJTFxxxxxxxxxxxxxxxxxxxxxxxxxx7IBTQEJFA5Z"
"open_ai_api_base": "https://ai.gitee.com/v1",
```
同时支持在对话中通过`#model`指令修改模型：`#model Qwen2.5-32B-Instruct`

add gitee-ai model resources that are compatible with openai format

---

bot/linkai/link_ai_bot.py

修复当返回内容只有图片URLs时，链接解析成图片直接返回，同时又返回了链接的问题~

fix: resolve display issue for replies containing only image URLs

---

bot/xunfei/xunfei_spark_bot.py

Reference: [Web API 接口说明](https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)的 `parameter.chat部分`。

fix: domain type of xunfei lite

---

common/const.py

DeepSeek模型接口兼容OpenAI接口，可以直接复用项目默认的chatGPT bot，接入配置如下：
```
"open_ai_api_key": "sk-589a4798c3a3d48fb74",
"open_ai_api_base": "https://api.deepseek.com/v1",
"model": "deepseek-chat",
```
- `"open_ai_api_key"`：填入密钥
- `"open_ai_api_base"`：填入api服务地址，DeepSeek官方api地址是：`"https://api.deepseek.com/v1"`，也可以填写其他服务商的地址
- `"model"`：官方的模型名称是`"deepseek-chat"`和` "deepseek-reasoner"`的，也可以填入其他服务商的模型名称
注：仅官方模型名称支持通过`#model`指令进行切换。

feat: Add support for deepseek-chat and deepseek-reasoner models

---

README.md
bot/bot_factory.py
bot/modelscope/modelscope_bot.py
bot/modelscope/modelscope_session.py
bridge/bridge.py
common/const.py
config.py
plugins/godcmd/godcmd.py
plugins/role/role.py

新增ModelScope API-Inference支持的模型资源，目前支持的对话模型列表和文生图模型列表较多，部分对话模型列表如下：
```chatinput
["Qwen/QwQ-32B", "deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-Coder-32B-Instruct", "Qwen/Qwen2.5-Coder-14B-Instruct", "Qwen/Qwen2.5-Coder-7B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-32B-Instruct", "Qwen/Qwen2.5-14B-Instruct", "Qwen/Qwen2.5-7B-Instruct", "Qwen/QwQ-32B-Preview"]
```
更多模型可以参考：[modelscope-api](https://www.modelscope.cn/models?filter=inference_type&page=1)\
API_KEY获取：在魔搭社区用户中心免费获取使用，需要绑定阿里云账号，参考[文档](https://modelscope.cn/docs/model-service/API-Inference/intro)\
配置文件修改(需要文生图功能要配置“text_to_image参数”，更多文生图模型ID可参考[文生图模型库](http://modelscope.cn/models?filter=inference_type&page=1&tasks=hotTask%3Atext-to-image-synthesis&type=tasks))：
```chatinput
"bot_type": …
```

Add support for ModelScope API-Inference

---

channel/chat_channel.py
channel/web/web_channel.py

When `context` is `None`, it should not be used for assignment operations.
Adjusted the code logic to ensure that `context` is not `None` before performing any item assignment.

Fix: fix 'NoneType' object does not support item assignment error (#2525)

---

voice/baidu/baidu_voice.py

百度TTS语音合成513错误代码 #1037
https://github.com/zhayujie/chatgpt-on-wechat/issues/1037

fix: 修复百度语音合成长文处理
