zhayujie/chatgpt-on-wechat

bot/openai/open_ai_bot.py
channel/wechat/wechat_channel.py

add retry mechanism for openai.error.RateLimitError

fix: handle RateLimitError #50 #54

---

bot/chatgpt/chat_gpt_bot.py

[feat] catch connection failed exception

---

bot/chatgpt/chat_gpt_bot.py

1、补充chatbot的函数discard_exceed_conversation
2、补充清理会话内存功能，比较经济做法

增加处理会话超长问题

---

bot/chatgpt/chat_gpt_bot.py

fix a minor typo

---

bot/chatgpt/chat_gpt_bot.py

feature: 消息控制配置热更新

---

docker/docker-compose.yaml
docker/entrypoint.sh
docker/sample-chatgpt-on-wechat/.env

add `speech_recognition` configuration . ref: #415, #385
change `sed` expression to match configurations via name instead of line number.
File-Changes:
*:   docker/docker-compose.yaml
*:   docker/entrypoint.sh
*:   docker/sample-chatgpt-on-wechat/.env
Refs: [#b204d30](https://github.com/zhayujie/chatgpt-on-wechat/commit/b204d305a15029d4cacac2d8f2bea6772c812746)

feat: container support speech recognition

---

bot/chatgpt/chat_gpt_bot.py
bridge/bridge.py
config.py

1.  要求可选的配置项都填写在config.py中，避免配置项混乱和读取所有环境变量
2.  添加语音api的设置
3.  增加AzureChatGPTBot的代码复用

feat: add options to set voice bot

---

config.py
docker/Dockerfile.latest
docker/build.latest.sh
docker/docker-compose.yaml
docker/entrypoint.sh

使用环境变量来为docker传参，merge后需release。

docker: use environment vars  to set parameters

---

app.py
channel/channel.py
channel/chat_channel.py
channel/chat_message.py
channel/wechat/wechat_channel.py
channel/wechat/wechat_message.py
channel/wechat/wechaty_channel.py
channel/wechat/wechaty_message.py
voice/audio_convert.py

1. 重构 wechaty和itchat共用一套逻辑，避免两个channel逻辑不同步
2. wechaty支持插件

wechaty支持插件

---

voice/azure/azure_voice.py
voice/baidu/baidu_voice.py
voice/google/google_voice.py
voice/pytts/pytts_voice.py

fix: Avoid the same filename under multithreading

---

requirements-optional.txt

1. 支持azure、api转发服务
2. 修复browser代理无前缀报错的问题
3. 优化core prompt
4. 修复系列issue提到的问题

plugin(tool): 更新0.4.4

---

channel/chat_channel.py

add \n after @nickname for group chat

---

channel/chat_channel.py
config.py

Add optional configuration parameters for automatic reply suffixes in group chat and single chat.

add reply_suffix

---

plugins/source.json

内置 timetask 插件

---

plugins/keyword/keyword.py

增加返回图片的功能。以http/https开头，且以.jpg/.jpeg/.png/.gif结尾的内容，识别为URL，自动以图片发送。

Update keyword.py 增加返回图片的功能

---

config.py
voice/elevent/elevent_voice.py
voice/factory.py

调用ElevenLabs进行语音回复，卓越、地道的美音、英音，很适合用于英文语音互动类产品。
1.使用前需要用安装elevenlabs依赖库pip install elevenlabs
2.在config.json中查看对应的elevenlabs字典项
3.在config.json中进行字典配置
4.亲测wechat中运行elevenlabs提供的9个音库，均有效。

add ElevenLabs TTS to voice factory

---

app.py
bridge/context.py
bridge/reply.py
channel/channel_factory.py
channel/chat_channel.py
channel/chat_message.py
channel/wework/run.py
channel/wework/wework_channel.py
channel/wework/wework_message.py
config.py

新增支持wework企业微信机器人
README.md：
PC本地部署wework（仅限window平台）
1.主项目安装主要依赖后，还需要安装ntwork依赖
```
pip install ntwork
```
2.安装指定PC企微专用版本：[WeCom_4.0.8.6027版本](https://dldir1.qq.com/wework/work_weixin/WeCom_4.0.8.6027.exe)，扫码登陆好，关闭自动更新企业微信
3.修改主项目配置项：config.json文件内
```json
"channel_type": "wework"
"wework_smart": true
```
4.运行 app.py
===============================================================
特别鸣谢：chazzjimel 跃迁(https://github.com/chazzjimel)
https://github.com/chazzjimel/WeChat-AIChatbot-WinOnly
主要基于该开源代码修复一些导致脚本无法正常运行和响应的bug，已在本地试验成功。。。

支持wework企业微信机器人

---

channel/wework/wework_channel.py
requirements-optional.txt

对齐其他channel图片处理逻辑，可选依赖文件增加wework所需依赖！

Optimize image download and storage logic

---

channel/wechatmp/wechatmp_channel.py

企业服务号的语音输出进行切割

---

channel/wechatmp/passive_reply.py
channel/wechatmp/wechatmp_channel.py

1、支持长语音：语音超过60s，会分段缓存。一次请求获取60s，直至完全获取！
2、支持一次请求产生多个回复消息：比如linkai的mj作图，可以等待作图完成，发消息获取图片，再次发消息，获取帮助信息！

个人订阅号消息存储优化

---

channel/chat_channel.py

chatgpt-on-wechat    | [ERROR][2023-09-27 18:48:41][chat_channel.py:211] - [WX] unknown context type: SHARING

Update chat_channel.py fix SHARING Type 报错。

---

bridge/context.py
channel/wechat/wechat_channel.py
channel/wechat/wechat_message.py
config.py
plugins/hello/hello.py

后面还打算想办法加用户自己退出的提醒，目前版本是可以在群主（且群主/管理员自己是bot）踢人时候发出提醒
操作系统：macos
运行的python版本：Python 3.11.4
运行的channel：wechat
已经在本地测试过

adding features: 退群提醒

---

voice/ali/ali_api.py
voice/ali/ali_voice.py
voice/ali/config.json.template
voice/factory.py

add ali voice output

---

plugins/tool/README.md
plugins/tool/config.json.template
plugins/tool/tool.py
requirements-optional.txt

1. 新增工具pure模式，支持单个工具调用
2. 新增消息转发工具：email, sms, wechat, 可以根据规则向其他平台发送消息
3. 替换visual-dl（更名为visual）实现，目前识别图片链接效果较好。
4. 修复了0.4版本大部分工具返回结果不可靠问题

tool 0.5.0

---

README.md

不必单独创建nohup.out文件
nohup 命令执行时会自动创建

Doc: 优化【服务器部署】

---

bot/bot_factory.py
bot/zhipu/chat_glm_bot.py
bot/zhipu/chat_glm_session.py
bridge/bridge.py
common/const.py
config.py
requirements-optional.txt

feat: 增加智谱chatglm4模型支持

---

voice/audio_convert.py
voice/baidu/baidu_voice.py

百度语音转写支持8000采样率, pcm_s16le编码, 单通道语音的组合

---

plugins/godcmd/godcmd.py

add feature 优化智谱 AI 的命令操作，使其支持重置会话

---

bot/bot_factory.py
bot/dashscope/dashscope_bot.py
bot/dashscope/dashscope_session.py
bridge/bridge.py
common/const.py
config.py
requirements-optional.txt

现在项目使用的通义千问是旧版本的百炼sdk，
这里增加一个新版本sdk(dashscope)的实现

feat: 通义千问使用新版的sdk实现

---

bot/bot_factory.py
bot/moonshot/moonshot_bot.py
bot/moonshot/moonshot_session.py
bridge/bridge.py
config.py

moonshot本来可直接使用openai sdk，
但是要求openai sdk必须在1.0以上，与本项目冲突，
故现使用http接口对接的方式集成

feat: 增加moonshot api集成

---

config.py

fix: baidu voice bug

---

common/time_check.py

1、考虑了跨天的情况
2、时间字符串转为时间结构体，便于比较大小

fix: time_check model

---

config.py

feat: add logger drag sensitive

---

bot/bot_factory.py
bot/minimax/minimax_bot.py
bot/minimax/minimax_session.py
bridge/bridge.py
common/const.py
config.py

feat#add minmax model

---

bot/gemini/google_gemini_bot.py
bridge/bridge.py
common/const.py

适配Gemini-1.5模型：
model参数可填："gemini", "gemini-1.5-pro"和"gemini-1.5-flash"，并支持移动端通过 #model 指令切换模型

Update gemini 1.5model

---

plugins/source.json

- 支持运用suno音乐组合AI进行图生音，文生音
- 支持运用AI进行文件总结，图片总结等
- 支持并发控制，管理员参数控制
- 支持对特定群聊模型和功能的控制
- 支持企业微信，个人号，公众号部署

PictureChange插件功能升级

---

config.py
voice/ali/ali_api.py
voice/ali/ali_voice.py
voice/ali/config.json.template

之前的语音识别部分，阿里云只有文字转语音，而没有语音转文字，实际上阿里是提供了免费接口的，现在我将其添加上去了
[智能语音交互RESTfulAPI ROA](https://help.aliyun.com/zh/isi/developer-reference/restful-api-2)

增加了使用阿里云进行语音识别的引擎

---

bot/chatgpt/chat_gpt_session.py
common/const.py
config.py

Support gpt-4o-mini model

---

channel/wechatcom/wechatcomapp_channel.py
config.py

兼容 /wxcomapp和 /wxcomapp/两种情况，解决#1813提到的问题

Ensure compatibility for /wxcomapp URL with trailing slash

---

channel/dingtalk/dingtalk_channel.py
channel/wechat/wechat_channel.py
plugins/role/role.py

1. role 角色扮演插件支持更多模型
2. 设置默认过期时间，解决没有配置`"expires_in_seconds"`参数导致的`TypeError: unsupported type for timedelta seconds component: NoneType  `错误

Fix issues

---

plugins/role/role.py

Optimize log information printing

Optimize log information printing

---

channel/wechat/wechat_message.py

Optimize the welcome message for new members.

---

bot/xunfei/xunfei_spark_bot.py

Xunfei supports system prompt(character_desc).

---

channel/wechat/wechat_channel.py
config.py

机器人在群内回复时，支持设置是否@提问者，默认需要@。
如不需要艾特，在根目录的config.json文件增加个参数:`"no_need_at": true,`

Support configuration whether to be @ in group chat.

---

bot/baidu/baidu_wenxin.py
config.py

Refer to:
https://console.bce.baidu.com/support/?_=1723772346802#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%B9%B3%E5%8F%B0&parent=ERNIE%20Character&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fernie-char-8k&method=post
ERNIE character model supports prompt.

wenxin character model supports prompt

---

bot/chatgpt/chat_gpt_session.py
common/const.py

配置model参数即可：
`"model": "gpt-4o-2024-08-06"`

feat: support gpt-4o-2024-08-06 model

---

common/linkai_client.py

fix: Linkai voice configuration

---

bot/gemini/google_gemini_bot.py

Gemini's default safety thresholds are set too high, resulting in frequent censorship of generated text. I have lowered the thresholds for all four safety categories according to Google's documentation.

Lower Gemini's safety thresholds

---

bridge/bridge.py
common/const.py

Zhipu AI recently made the API for the GLM-4-Flash model free, so I made simple code modifications to add support for GLM-4-Flash, as well as some other models from Zhipu AI.

Support more models from Zhipu AI

---

plugins/linkai/summary.py

Buy using app code, supports custom summary prompt .

---

plugins/role/role.py

Linkai bot is compatible with the role plugin.

---

app.py
channel/channel_factory.py
channel/web/README.md
channel/web/chat.html
channel/web/web_channel.py
config.py

使用SSE（Server-Sent Events，服务器推送事件）实现，提供了一个默认的网页。也可以自己实现加入api
#使用方法
- 在配置文件中channel_type填入web即可
- 访问地址 http://localhost:9899/chat
- port可以在配置项 web_port中设置

增加web channel

---

plugins/plugin_manager.py

fix: Memory leak caused by scanp command due to handler's reference of plugin instance

---

common/const.py

新增Gemini相关模型，`model` 参数为：` gemini-2.5-pro-preview-05-06、gemini-2.5-flash-preview-05-20、gemini-2.0-flash `

feat: update Gemini models
